spring:
  application:
    name: bus-management
  datasource:
    url: jdbc:h2:file:./testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
logging:
  level:
    root: INFO